# Form implementation generated from reading ui file 'UI/UIv1.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 595)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("QLineEdit {\n"
"background: transparent;\n"
"border-radius: none;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.Background_image = QtWidgets.QLabel(self.centralwidget)
        self.Background_image.setGeometry(QtCore.QRect(0, 0, 950, 600))
        font = QtGui.QFont()
        font.setFamily("MS Reference Specialty")
        font.setBold(False)
        font.setWeight(50)
        self.Background_image.setFont(font)
        self.Background_image.setText("")
        self.Background_image.setPixmap(QtGui.QPixmap(":/newPrefix/Form1.png"))
        self.Background_image.setScaledContents(False)
        self.Background_image.setObjectName("Background_image")
        self.Calculate_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Calculate_Button.setGeometry(QtCore.QRect(750, 530, 171, 51))
        self.Calculate_Button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Calculate_Button.setStyleSheet("backgroun: transparent;\n"
"border: none;")
        self.Calculate_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Calculate.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Calculate_Button.setIcon(icon)
        self.Calculate_Button.setIconSize(QtCore.QSize(170, 60))
        self.Calculate_Button.setCheckable(False)
        self.Calculate_Button.setChecked(False)
        self.Calculate_Button.setAutoRepeatDelay(300)
        self.Calculate_Button.setObjectName("Calculate_Button")
        self.TextBox_City = QtWidgets.QLineEdit(self.centralwidget)
        self.TextBox_City.setGeometry(QtCore.QRect(490, 150, 411, 41))
        self.TextBox_City.setStyleSheet("QLineEdit {\n"
"background: transparent;\n"
"border-radius: none;\n"
"font-size: 17px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.TextBox_City.setObjectName("TextBox_City")
        self.TextBox_Street = QtWidgets.QLineEdit(self.centralwidget)
        self.TextBox_Street.setGeometry(QtCore.QRect(490, 216, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.TextBox_Street.setFont(font)
        self.TextBox_Street.setStyleSheet("QLineEdit {\n"
"background: transparent;\n"
"border-radius: none;\n"
"font-size: 17px;\n"
"}\n"
"")
        self.TextBox_Street.setObjectName("TextBox_Street")
        self.TextBox_Floor = QtWidgets.QLineEdit(self.centralwidget)
        self.TextBox_Floor.setGeometry(QtCore.QRect(500, 338, 141, 35))
        self.TextBox_Floor.setStyleSheet("QLineEdit {\n"
"background: transparent;\n"
"border-radius: none;\n"
"font-size: 17px;\n"
"}\n"
"")
        self.TextBox_Floor.setPlaceholderText("")
        self.TextBox_Floor.setObjectName("TextBox_Floor")
        self.TextBox_Number_Floors = QtWidgets.QLineEdit(self.centralwidget)
        self.TextBox_Number_Floors.setGeometry(QtCore.QRect(768, 338, 141, 35))
        self.TextBox_Number_Floors.setStyleSheet("QLineEdit {\n"
"background: transparent;\n"
"border-radius: none;\n"
"font-size: 17px;\n"
"}\n"
"")
        self.TextBox_Number_Floors.setPlaceholderText("")
        self.TextBox_Number_Floors.setObjectName("TextBox_Number_Floors")
        self.TextBox_Year_Construction = QtWidgets.QLineEdit(self.centralwidget)
        self.TextBox_Year_Construction.setGeometry(QtCore.QRect(500, 390, 141, 41))
        self.TextBox_Year_Construction.setStyleSheet("QLineEdit {\n"
"background: transparent;\n"
"border-radius: none;\n"
"font-size: 17px;\n"
"}\n"
"")
        self.TextBox_Year_Construction.setPlaceholderText("")
        self.TextBox_Year_Construction.setObjectName("TextBox_Year_Construction")
        self.TextBox_Number_Rooms = QtWidgets.QLineEdit(self.centralwidget)
        self.TextBox_Number_Rooms.setGeometry(QtCore.QRect(768, 394, 141, 34))
        self.TextBox_Number_Rooms.setStyleSheet("QLineEdit {\n"
"background: transparent;\n"
"border-radius: none;\n"
"font-size: 17px;\n"
"}\n"
"")
        self.TextBox_Number_Rooms.setPlaceholderText("")
        self.TextBox_Number_Rooms.setObjectName("TextBox_Number_Rooms")
        self.TextBox_General = QtWidgets.QLineEdit(self.centralwidget)
        self.TextBox_General.setGeometry(QtCore.QRect(504, 451, 51, 31))
        self.TextBox_General.setStyleSheet("QLineEdit {\n"
"background: transparent;\n"
"border-radius: none;\n"
"font-size: 17px;\n"
"}\n"
"")
        self.TextBox_General.setClearButtonEnabled(False)
        self.TextBox_General.setObjectName("TextBox_General")
        self.TextBox_Residential_rea = QtWidgets.QLineEdit(self.centralwidget)
        self.TextBox_Residential_rea.setGeometry(QtCore.QRect(679, 451, 51, 31))
        self.TextBox_Residential_rea.setStyleSheet("QLineEdit {\n"
"background: transparent;\n"
"border-radius: none;\n"
"font-size: 17px;\n"
"}\n"
"")
        self.TextBox_Residential_rea.setObjectName("TextBox_Residential_rea")
        self.TextBox_Kitchen = QtWidgets.QLineEdit(self.centralwidget)
        self.TextBox_Kitchen.setGeometry(QtCore.QRect(854, 451, 51, 31))
        self.TextBox_Kitchen.setStyleSheet("QLineEdit {\n"
"background: transparent;\n"
"border-radius: none;\n"
"font-size: 17px;\n"
"}\n"
"")
        self.TextBox_Kitchen.setObjectName("TextBox_Kitchen")
        self.Line_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Line_Button.setGeometry(QtCore.QRect(75, 270, 250, 51))
        self.Line_Button.setStyleSheet("backgroun: transparent;\n"
"border: none;")
        self.Line_Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Line.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Line_Button.setIcon(icon1)
        self.Line_Button.setIconSize(QtCore.QSize(250, 100))
        self.Line_Button.setCheckable(False)
        self.Line_Button.setChecked(False)
        self.Line_Button.setAutoRepeatDelay(300)
        self.Line_Button.setObjectName("Line_Button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 240, 401, 61))
        self.label.setStyleSheet("font-size: 32px;\n"
"color: white;")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 290, 391, 61))
        self.label_2.setStyleSheet("font-size: 32px;\n"
"color: white;")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 12, 40, 40))
        self.pushButton.setStyleSheet("background: transparent;")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/samolet_logo_white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(60, 60))
        self.pushButton.setObjectName("pushButton")
        self.Clear_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Clear_Button.setGeometry(QtCore.QRect(570, 530, 171, 51))
        self.Clear_Button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Clear_Button.setStyleSheet("backgroun: transparent;\n"
"border: none;")
        self.Clear_Button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/Clear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Clear_Button.setIcon(icon3)
        self.Clear_Button.setIconSize(QtCore.QSize(170, 60))
        self.Clear_Button.setCheckable(False)
        self.Clear_Button.setChecked(False)
        self.Clear_Button.setAutoRepeatDelay(300)
        self.Clear_Button.setObjectName("Clear_Button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TextBox_City.setPlaceholderText(_translate("MainWindow", "пример: Москва"))
        self.TextBox_Street.setPlaceholderText(_translate("MainWindow", "пример: Комсомольская"))
        self.TextBox_General.setPlaceholderText(_translate("MainWindow", "...M²"))
        self.TextBox_Residential_rea.setPlaceholderText(_translate("MainWindow", "...М²"))
        self.TextBox_Kitchen.setPlaceholderText(_translate("MainWindow", "...М²"))
